version: '3.9'

services:
  app:
    image: my-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DISCORD_WEBHOOK_URL
    command: node server.js