version: '3'
services:
  app:
    image: plex-webhook-server
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DISCORD_WEBHOOK_URL
    command: node server.js